nodes: 8
tasks_per_node: 8
tag: img-reconstruction-in1k
eval_name: image_reconstruction_frozen
resume_checkpoint: false
data_path: /home/vschorp/self_supervised_bucket/data/
data:
  image_folder: datasets/imagenet_full_size/061417/
  num_classes: 1000
  resolution: 224
  dataset_name: ImageNet
optimization:
  num_epochs: 20
  batch_size: 8
  weight_decay: 0.001
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: false
pretrain:
  model_name: vit_large
  encoder_checkpoint_key: encoder
  predictor_checkpoint_key: predictor
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_sdpa: true
  use_silu: false
  tight_silu: false
  patch_size: 16
  pred_depth: 12
  pred_embed_dim: 384
  use_mask_tokens: true
  zero_init_mask_tokens: true
  folder: checkpoints/
  checkpoint: pretrain/vitl16.pth.tar  # name of pretrained model file inside folder
  write_tag: jepa
mask:
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 8
    spatial_scale:
      - 0.15
      - 0.15
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 2
    spatial_scale:
      - 0.7
      - 0.7
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
image_transforms:
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]